
/**
* ICommandHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ICommand.idl
* Wednesday, April 2, 2014 5:04:48 PM CEST
*/

abstract public class ICommandHelper
{
  private static String  _id = "IDL:ICommand:1.0";

  public static void insert (org.omg.CORBA.Any a, ICommand that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ICommand extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ICommandHelper.id (), "ICommand");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ICommand read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ICommandStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ICommand value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ICommand narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ICommand)
      return (ICommand)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _ICommandStub stub = new _ICommandStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ICommand unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ICommand)
      return (ICommand)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _ICommandStub stub = new _ICommandStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
