
/**
* ICommandOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ICommand.idl
* vendredi 4 avril 2014 11 h 31 CEST
*/

public interface ICommandOperations 
{
  boolean SendCommand (String cmd, String args);
} // interface ICommandOperations
