
/**
* ICommand.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ICommand.idl
* Wednesday, April 2, 2014 4:52:56 PM CEST
*/

public interface ICommand extends ICommandOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ICommand
