
/**
* ICommand.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ICommand.idl
* vendredi 4 avril 2014 11 h 31 CEST
*/

public interface ICommand extends ICommandOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ICommand
