
/**
* ICommandHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ICommand.idl
* vendredi 4 avril 2014 11 h 31 CEST
*/

public final class ICommandHolder implements org.omg.CORBA.portable.Streamable
{
  public ICommand value = null;

  public ICommandHolder ()
  {
  }

  public ICommandHolder (ICommand initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ICommandHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ICommandHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ICommandHelper.type ();
  }

}
