
/**
* ICommandOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ICommand.idl
* Wednesday, April 2, 2014 5:12:38 PM CEST
*/

public interface ICommandOperations 
{
  boolean SendCommand (String cmd, String args);
} // interface ICommandOperations
