
/**
* ICommand.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ICommand.idl
* mercredi 9 avril 2014 14 h 45 CEST
*/

public interface ICommand extends ICommandOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ICommand
